applicationName: Base Kotlin

web:
  corsOrigins: "*"
  openApi: false
  baseEncodeJson: false

instances:
  org.ktlib.email.Email: org.ktlib.email.SendGrid
  org.ktlib.entities.EntityInitializer: adapters.db.EntityInitializer

email:
  defaultFrom: noreply@ktlib.org
  defaultFromName: Kotlin
  verificationTemplate: fakeVerificationTemplate
  forgotPasswordTemplate: fakeForgotPasswordTemplate
  userInviteTemplate: fakeUserInviteTemplate
  sendgrid:
    apiKey: $SENDGRID_API_KEY

db:
  type: Postgres
  driver: org.postgresql.Driver