applicationName: Base Kotlin
bootstrap: infrastructure.Bootstrap

web:
  corsOrigins: "*"
  openApi: false
  baseEncodeJson: false

email:
  defaultFrom: noreply@ktlib.org
  defaultFromName: Kotlin
  verificationTemplate: fakeVerificationTemplate
  forgotPasswordTemplate: fakeForgotPasswordTemplate
  userInviteTemplate: fakeUserInviteTemplate
  sendgrid:
    apiKey: $SENDGRID_API_KEY

db:
  type: Postgres
  driver: org.postgresql.Driver