name: CI

on: [ push ]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build:
    name: Unit Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.2
        env:
          POSTGRES_USER: local
          POSTGRES_PASSWORD: local
          POSTGRES_DB: app
        ports:
          - "5444:5432"
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Run Tests
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: migrate test

      - name: Test Report
        uses: dorny/test-reporter@v3
        if: success() || failure()
        with:
          name: Unit Test Results
          path: build/test-results/**/*.xml
          reporter: java-junit
          fail-on-error: false
